language: ruby
cache: bundler
rvm:
  - '1.9.3'
  - '2.5'
jobs:
  include: 
    - rvm: jruby-19mode
      jdk: openjdk8
    - rvm: jruby-19mode
      jdk: openjdk11
    - rvm: jruby-9.2.19.0
      jdk: openjdk8
    - rvm: jruby-9.2.19.0
      jdk: openjdk11
# before_script:
  # - cp config/settings.example.yml config/settings.yml
env:
  - COVERAGE=on
notifications:
  email:
    recipients:
      - cintegration@assetricity.com
bundler_args: --without debugging
script:
  - bundle config set --local path 'vendor/bundle'
  - bundle install
  - bundle exec rspec
  - gem build isbm2_adaptor_rest.gemspec
  - gem install ./isbm2_adaptor_rest-2.0.0.gem
