=begin
#ISBM 2.0

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for IsbmRestAdaptor::ConfigurationDiscoveryServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConfigurationDiscoveryServiceApi' do
  before do
    # run before each test
    @api_instance = IsbmRestAdaptor::ConfigurationDiscoveryServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConfigurationDiscoveryServiceApi' do
    it 'should create an instance of ConfigurationDiscoveryServiceApi' do
      expect(@api_instance).to be_instance_of(IsbmRestAdaptor::ConfigurationDiscoveryServiceApi)
    end
  end

  # unit tests for get_security_details
  # Gets the detailed security related information of the ISBM service provider. The security details are exposed only if the connecting application provides a valid SecurityToken. Each application may be assigned a SecurityToken out-of-band by the service provider.
  # @param [Hash] opts the optional parameters
  # @return [SecurityDetails]
  describe 'get_security_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_supported_operations
  # Gets information about the supported operations and features of the ISBM service provider. The purpose of this operation is to allow an application to be configured appropriately to communicate successfully with the service provider.
  # @param [Hash] opts the optional parameters
  # @return [SupportedOperations]
  describe 'get_supported_operations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
