=begin
#ws-ISBM

#A prototype OpenAPI specification for the ws-ISBM RESTful interface.

OpenAPI spec version: 0.0.1
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'

# Unit tests for IsbmRestAdaptor::ProviderPublicationServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProviderPublicationServiceApi' do
  before do
    # run before each test
    @instance = IsbmRestAdaptor::ProviderPublicationServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProviderPublicationServiceApi' do
    it 'should create an instance of ProviderPublicationServiceApi' do
      expect(@instance).to be_instance_of(IsbmRestAdaptor::ProviderPublicationServiceApi)
    end
  end

  # unit tests for close_session
  # Closes a session.
  # Closes a session of any type. **Note** this diverges from the SOAP API in that it provides a single path for sessions of all types. The type of session is still known upon creation and the different operations can still only be performed on sessions of the correct type. All unexpired messages that have been posted during the session will be expired.
  # @param session_id The identifier of the session to be accessed (retrieved, deleted, modified, etc.)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'close_session test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expire_publication
  # Expires a posted publication.
  # @param session_id The identifier of the session to which the publication was posted.
  # @param message_id The identifier of the poosted publication.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'expire_publication test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for open_publication_session
  # Opens a publication session for a channel.
  # @param channel_id The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)
  # @param [Hash] opts the optional parameters
  # @return [Session]
  describe 'open_publication_session test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_publication
  # Posts a publication message on a channel.
  # @param session_id The identifier of the session to which the message will/is posted.
  # @param topic The Topic(s) to which the message will be posted.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expiry The duration after which the message will be automatically expired. Negative duration is no duration.
  # @option opts [Hash<String, Object>] :request_body The Message. All ISBM service providers MUST support JSON and XML content types. ISBM service providers MAY support arbitrary content types.
  # @return [Message]
  describe 'post_publication test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
