=begin
A common superclass for the API classes to allow reuse of shared application logic.
This is *not* generated by the OpenAPI tooling.
=end

require 'erb'

module ISBMRestAdaptor
  class ApplicationApi
    include ERB::Util
  end
end