=begin
#ISBM 2.0

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IsbmRestAdaptor::ChannelFault
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IsbmRestAdaptor::ChannelFault do
  let(:instance) { IsbmRestAdaptor::ChannelFault.new }

  describe 'test an instance of ChannelFault' do
    it 'should create an instance of ChannelFault' do
      expect(instance).to be_instance_of(IsbmRestAdaptor::ChannelFault)
    end
  end
  describe 'test attribute "fault"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
