=begin
#ISBM 2.0

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ISBMRestAdaptor::FilterExpressionExpressionString
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ISBMRestAdaptor::FilterExpressionExpressionString do
  let(:instance) { ISBMRestAdaptor::FilterExpressionExpressionString.new }

  describe 'test an instance of FilterExpressionExpressionString' do
    it 'should create an instance of FilterExpressionExpressionString' do
      expect(instance).to be_instance_of(ISBMRestAdaptor::FilterExpressionExpressionString)
    end
  end
  describe 'test attribute "expression"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "language"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "language_version"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
