=begin
#ISBM 2.0 Notification Service

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ISBMRestAdaptor::Notification
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ISBMRestAdaptor::Notification do
  let(:instance) { ISBMRestAdaptor::Notification.new }

  describe 'test an instance of Notification' do
    it 'should create an instance of Notification' do
      expect(instance).to be_instance_of(ISBMRestAdaptor::Notification)
    end
  end
  describe 'test attribute "session_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "topics"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "request_message_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
