=begin
#ISBM 2.0

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ISBMRestAdaptor::OperationFault
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OperationFault' do
  before do
    # run before each test
    @instance = ISBMRestAdaptor::OperationFault.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OperationFault' do
    it 'should create an instance of OperationFault' do
      expect(@instance).to be_instance_of(ISBMRestAdaptor::OperationFault)
    end
  end
  describe 'test attribute "faultstring"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["The channel type must be the Publication type", "The channel type must be the Request type"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.faultstring = value }.not_to raise_error
      # end
    end
  end

end
