=begin
#ISBM 2.0

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IsbmRestAdaptor::SessionFault
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SessionFault' do
  before do
    # run before each test
    @instance = IsbmRestAdaptor::SessionFault.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionFault' do
    it 'should create an instance of SessionFault' do
      expect(@instance).to be_instance_of(IsbmRestAdaptor::SessionFault)
    end
  end
  describe 'test attribute "faultstring"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["The session type must be Publication Provider for this operation", "The session type must be Publication Consumer for this operation", "The session type must be Request Provider for this operation", "The session type must be Request Consumer for this operation"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.faultstring = value }.not_to raise_error
      # end
    end
  end

end
