=begin
#ISBM 2.0

#An OpenAPI specification for the ISBM 2.0 RESTful interface.

The version of the OpenAPI document: 2.0
Contact: info@mimosa.org
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ISBMRestAdaptor::SupportedOperationsSupportedAuthentications
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ISBMRestAdaptor::SupportedOperationsSupportedAuthentications do
  let(:instance) { ISBMRestAdaptor::SupportedOperationsSupportedAuthentications.new }

  describe 'test an instance of SupportedOperationsSupportedAuthentications' do
    it 'should create an instance of SupportedOperationsSupportedAuthentications' do
      expect(instance).to be_instance_of(ISBMRestAdaptor::SupportedOperationsSupportedAuthentications)
    end
  end
  describe 'test attribute "soap_supported_token_schemas"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rest_supported_authentication_schemes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
